#pragma once

// TODO-----------------------------------------------------------------
// [small]  replace(): `else if (!t2_.empty())` silently does nothing when both
//          T1 and T2 are empty. Convince yourself this branch is unreachable
//          (see invariants) and consider replacing it with an assert.
// [small]  store()/evict_to_ghost() use hash_[key] / ghost_hash_[key]
//          (operator[]): same question as in LRU/LFU - emplace/insert_or_assign?
// [small]  make_room(), branch "T1 took the whole cache": why is the evicted
//          page dropped WITHOUT a ghost here? (hint: |T1| + |B1| <= cap_)
// [medium] Exception safety: unlike LRU/LFU, slow_get_page() is called AFTER
//          replace()/make_room(). If it throws, a page is already evicted and
//          the ghost is erased. Move the load to the top of cases II-IV.
// [medium] Ghost case: `const ghost_elem_t& gelem = ghost->second` is taken
//          before replace(). Revert to `ghost->second` after replace() and
//          build with -D_GLIBCXX_DEBUG -fsanitize=address: does it catch it?
//          Find the rule for unordered_map (iterators vs references on rehash).
// [medium] Only invariant 1 is asserted. Write a private
//          `bool check_invariants() const` (sizes of lists vs maps, in_t2/in_b2
//          flags, |T1|+|B1| <= cap_, total <= 2*cap_) and assert it at the end
//          of lookup_update() in debug builds.
// [medium] adapt() uses integer division, the paper uses a real-valued p.
//          Try `double p_` and compare hit counts on long random inputs.
// [medium] Two hash tables because list<page_t>::iterator and
//          list<KeyT>::iterator are different types. Think about the
//          alternatives (std::variant, one map + flag) and their trade-offs.
// [big]    T is copied several times per miss, same as in LRU/LFU.
// [big]    Google tests: capacity 0, 1, 2; a ghost hit in B1 grows p_, in B2
//          shrinks it; scan resistance (hot keys survive a long scan, compare
//          with LRU); expected values can be generated by the Python reference.
// [big]    Compare LRU / LFU / ARC with `./cache all` on different workloads:
//          a loop slightly bigger than the cache, a changing hot set, a scan.
// --------------------------------------------------------------------------

#include <algorithm>
#include <cassert>
#include <cstddef>
#include <list>
#include <unordered_map>
#include <utility>

namespace caches {

// ARC (Adaptive Replacement Cache), Megiddo & Modha, 2003.
//
// cap_ cached pages are split between two LRU lists:
//   T1 - pages requested once        (recency)
//   T2 - pages requested >= 2 times  (frequency)
// Next to them live two lists of "ghosts" - keys of evicted pages, no data:
//   B1 - evicted from T1,  B2 - evicted from T2
// p_ is the target size of T1 (so the target of T2 is cap_ - p_). A ghost hit
// moves p_ towards the list that was short of space.
//
// Invariants: |T1| + |T2| <= cap_,  |T1| + |B1| <= cap_,
//             |T1| + |T2| + |B1| + |B2| <= 2 * cap_
//             a key is in at most one of the four lists
//
// The public interface is the same as in lru_cache and lfu_cache:
// capacity / size / hits / misses / is_full / lookup_update.
template <typename T, typename KeyT>
class arc_cache {
private:
    // types
    struct page_t {
        T    content;
        KeyT key;
    };

    using list_t       = std::list<page_t>;
    using list_iter_t  = typename list_t::iterator;
    using ghost_t      = std::list<KeyT>;
    using ghost_iter_t = typename ghost_t::iterator;

    // where a page is: iterator into t1_ or t2_
    struct cache_elem_t {
        list_iter_t it;
        bool        in_t2;
    };
    // where a ghost is: iterator into b1_ or b2_
    struct ghost_elem_t {
        ghost_iter_t it;
        bool         in_b2;
    };

    using hmap_t  = std::unordered_map<KeyT, cache_elem_t>;
    using gmap_t  = std::unordered_map<KeyT, ghost_elem_t>;

    // members
    size_t cap_;
    size_t p_        = 0;
    size_t n_hits_   = 0;
    size_t n_misses_ = 0;

    list_t  t1_, t2_;     // pages,  [MRU ... LRU]
    ghost_t b1_, b2_;     // ghosts, [MRU ... LRU]
    hmap_t  hash_;        // key -> page in t1_/t2_
    gmap_t  ghost_hash_;  // key -> ghost in b1_/b2_

    // methods
    void store(list_t& list, bool in_t2, const page_t& page);
    void move_to_t2(cache_elem_t& elem);
    void evict_to_ghost(list_t& from, ghost_t& to, bool in_b2);
    void forget_ghost(ghost_t& ghosts);
    void erase_ghost(const KeyT& key, const ghost_elem_t& elem);
    void adapt(bool in_b2);
    void replace(bool x_in_b2);
    void make_room();

public:
    explicit arc_cache(size_t capacity) : cap_(capacity) {}
    arc_cache(const arc_cache&) = delete;
    arc_cache& operator=(const arc_cache&) = delete;

    size_t capacity() const {return cap_;}
    size_t size()     const {return hash_.size();}
    size_t hits()     const {return n_hits_;}
    size_t misses()   const {return n_misses_;}

    bool   is_full()  const;
    template <typename F> std::pair<T, bool> lookup_update(const KeyT& key, F slow_get_page);
};

template <typename T, typename KeyT>
bool arc_cache<T, KeyT>::is_full() const {
    assert(t1_.size() + t2_.size() <= cap_);
    return t1_.size() + t2_.size() == cap_;
}

template <typename T, typename KeyT>
template <typename F>
std::pair<T, bool> arc_cache<T, KeyT>::lookup_update(const KeyT& key, F slow_get_page) {
    if (cap_ == 0) {
        ++n_misses_;
        return {slow_get_page(key), false};
    }

    // case I: the page is cached (T1 or T2)
    auto hit = hash_.find(key);
    if (hit != hash_.end()) {
        cache_elem_t& elem = hit->second;
        move_to_t2(elem);

        ++n_hits_;
        return {elem.it->content, true};
    }

    // cases II and III: no page, but we remember its key (B1 or B2)
    auto ghost = ghost_hash_.find(key);
    if (ghost != ghost_hash_.end()) {
        // replace() may insert into ghost_hash_ and rehash it: that invalidates
        // the iterator `ghost`, but not a reference to the element
        const ghost_elem_t& gelem = ghost->second;
        const bool in_b2 = gelem.in_b2;

        adapt(in_b2);
        replace(in_b2);
        erase_ghost(key, gelem);

        page_t page {
            .content = slow_get_page(key),
            .key     = key
        };
        store(t2_, true, page);           // requested >= 2 times => straight to T2

        ++n_misses_;
        return {page.content, false};
    }

    // case IV: a brand new key
    make_room();

    page_t page {
        .content = slow_get_page(key),
        .key     = key
    };
    store(t1_, false, page);

    ++n_misses_;
    return {page.content, false};
}

// put the page to the front (MRU) of the given list
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::store(list_t& list, bool in_t2, const page_t& page) {
    list.push_front(page);
    hash_[page.key] = cache_elem_t{list.begin(), in_t2};
}

// hit: the page moves to the MRU end of T2 (splice keeps the iterator valid)
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::move_to_t2(cache_elem_t& elem) {
    t2_.splice(t2_.begin(), elem.in_t2 ? t2_ : t1_, elem.it);
    elem.in_t2 = true;
}

// eviction from the cache: data is dropped, the key stays as a ghost
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::evict_to_ghost(list_t& from, ghost_t& to, bool in_b2) {
    assert(!from.empty());
    KeyT key = from.back().key;

    hash_.erase(key);
    from.pop_back();

    to.push_front(key);
    ghost_hash_[key] = ghost_elem_t{to.begin(), in_b2};
}

// forget the oldest ghost of the list completely
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::forget_ghost(ghost_t& ghosts) {
    assert(!ghosts.empty());
    ghost_hash_.erase(ghosts.back());
    ghosts.pop_back();
}

// a ghost becomes a page again: remove it from its ghost list
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::erase_ghost(const KeyT& key, const ghost_elem_t& elem) {
    (elem.in_b2 ? b2_ : b1_).erase(elem.it);
    ghost_hash_.erase(key);
}

// move the target p_ after a ghost hit
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::adapt(bool in_b2) {
    assert(!b1_.empty() || !b2_.empty());

    if (!in_b2) {  // missed a T1 page => T1 was too small, grow p_
        size_t delta = (b1_.size() >= b2_.size()) ? 1 : b2_.size() / b1_.size();
        p_ = std::min(cap_, p_ + delta);
    } else {       // missed a T2 page => T2 was too small, shrink p_
        size_t delta = (b2_.size() >= b1_.size()) ? 1 : b1_.size() / b2_.size();
        p_ = (p_ > delta) ? p_ - delta : 0;
    }
}

// free one cache slot: the victim goes T1 -> B1 or T2 -> B2
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::replace(bool x_in_b2) {
    if (!t1_.empty() && (t1_.size() > p_ || (x_in_b2 && t1_.size() == p_))) {
        evict_to_ghost(t1_, b1_, false);
    } else if (!t2_.empty()) {
        evict_to_ghost(t2_, b2_, true);
    }
}

// make room for a brand new key (case IV)
template <typename T, typename KeyT>
void arc_cache<T, KeyT>::make_room() {
    if (t1_.size() + b1_.size() == cap_) {
        if (t1_.size() < cap_) {
            forget_ghost(b1_);   // B1 is not empty, L1 has no room
            replace(false);
        } else {
            // B1 is empty, T1 took the whole cache: drop LRU of T1, no ghost
            hash_.erase(t1_.back().key);
            t1_.pop_back();
        }
        return;
    }

    size_t total = t1_.size() + t2_.size() + b1_.size() + b2_.size();
    if (total < cap_)
        return;                  // the cache is not full yet

    if (total == 2 * cap_)
        forget_ghost(b2_);
    replace(false);
}

}
